services:
  - type: web
    name: treqtrace
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 -m gunicorn wsgi:app"   # <-- python3, not python
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true